version: '3.7'

services:
  postgres:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_DB: "AirTrafficControlDb"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "9100:5432"
    container_name: air_traffic_control_system